PACKAGE_NAME="ixgbe"
PACKAGE_VERSION="6.4.5"
BUILT_MODULE_NAME[0]="ixgbe"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/updates/drivers/net/ethernet/intel/ixgbe"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/src KSRC=/lib/modules/${kernelver}/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/src clean"
AUTOINSTALL="yes"
